### ISSUE TITLE
Add support for RelationShipView

### ISSUE THREAD

**Issue by jokiefer** [jokiefer/drf-spectecular-json-api#21]
### Discussed in https://github.com/jokiefer/drf-spectecular-json-api/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **n2ygk** July 24, 2024</sup>
See discussion at https://github.com/django-json-api/django-rest-framework-json-api/discussions/1082.  Moving that discussion here. I am trying to convert from using the built-in deprecated DRF & DJA OAS 3.x support to using drf-spectacular and drf-spectacular-jsonapi.

I'm testing against an existing project's `spectacular` branch: https://github.com/columbia-it/django-jsonapi-training/tree/spectacular

I had RelationShipViews which caused asserts to fail like this:
```
AssertionError: Expected view CourseTermRelationshipView to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
```

In removing all the RelationShipViews from my urls.conf, I was able to generate a good OAS schema, attached as [drf-spectacular-jsonapi-no-relationships-yaml.txt](https://github.com/user-attachments/files/16367509/drf-spectacular-jsonapi-no-relationships-yaml.txt). It is generated with the following management command in the [spectacular](https://github.com/columbia-it/django-jsonapi-training/tree/spectacular) branch of my project:
```
(venv) django-jsonapi-training$ python manage.py spectacular --file drf-spectacular-jsonapi-no-relationships-yaml.txt
/Users/ac45/src/django-jsonapi-training/venv/lib/python3.12/site-packages/drf_spectacular_jsonapi/schemas/utils.py:14: UserWarning: Can't resolve primary key for non model serializers.
  warn(message="Can't resolve primary key for non model serializers.")
/Users/ac45/src/django-jsonapi-training/myapp/views.py:210: Warning [CourseTermViewSet]: could not derive type of path parameter "related_field" because model "myapp.models.CourseTerm" contained no such field. Consider annotating parameter with @extend_schema. Defaulting to "string".
/Users/ac45/src/django-jsonapi-training/myapp/views.py:186: Warning [CourseViewSet]: could not derive type of path parameter "related_field" because model "myapp.models.Course" contained no such field. Consider annotating parameter with @extend_schema. Defaulting to "string".
/Users/ac45/src/django-jsonapi-training/myapp/views.py:298: Warning [InstructorViewSet]: could not derive type of path parameter "related_field" because model "myapp.models.Instructor" contained no such field. Consider annotating parameter with @extend_schema. Defaulting to "string".
/Users/ac45/src/django-jsonapi-training/myapp/views.py:226: Warning [PersonViewSet]: could not derive type of path parameter "related_field" because model "myapp.models.Person" contained no such field. Consider annotating parameter with @extend_schema. Defaulting to "string".
Warning: operationId "course_terms_retrieve" has collisions [('/v1/course_terms/{id}/', 'get'), ('/v1/course_terms/{id}/{related_field}/', 'get')]. resolving with numeral suffixes.
Warning: operationId "courses_retrieve" has collisions [('/v1/courses/{id}/', 'get'), ('/v1/courses/{id}/{related_field}/', 'get')]. resolving with numeral suffixes.
Warning: operationId "instructors_retrieve" has collisions [('/v1/instructors/{id}/', 'get'), ('/v1/instructors/{id}/{related_field}/', 'get')]. resolving with numeral suffixes.
Warning: operationId "people_retrieve" has collisions [('/v1/people/{id}/', 'get'), ('/v1/people/{id}/{related_field}/', 'get')]. resolving with numeral suffixes.

Schema generation summary:
Warnings: 8 (8 unique)
Errors:   0 (0 unique)
```
You'll note the warnings about non-model serializers as well as the `related_field` warnings.

Compare this to [openapi-yaml.txt](https://github.com/user-attachments/files/16367510/openapi-yaml.txt) which was generated using the deprecated DJA OAS support plus some extensions I'd implemented. It is generated using this management command in the [master](https://github.com/columbia-it/django-jsonapi-training/tree/master) branch:
```
python manage.py generateschema  --generator_class myapp.schemas.SchemaGenerator --file openapi-yaml.txt
```

I believe the issue is that `class RelationshipView(generics.GenericAPIView)` is not based on a `ModelViewSet` as is typically used. So I think some enhancements are needed to support GenericAPIView.</div>

**Comment by n2ygk** [comment]
Oops #24
