### ISSUE TITLE
[Bug] KeyError: 'id' at build_json_api_resource_object func

### ISSUE THREAD

**Issue by jokiefer** [jokiefer/drf-spectecular-json-api#4]
### Identified as BUG

- [X] it is a bug!

### drf-spectacular-json-api version

v0.1.0

### Steps to Reproduce

1. Configure a non `Modelserializer` such as `rest_framework_json_api.serializers.Serializer inside your api and don't add an `id` field
2. build the schema

### Expected Behavior

* the schema shall be build for a non model serializer
* the be build for a serializer with an other named id property

### Observed Behavior

KeyError: 'id' is raised

**Comment by jokiefer** [comment]
@sliverc i need a little help with this. 
Look at the [L85](https://github.com/jokiefer/drf-spectecular-json-api/blob/12325637e1426aaa7e78b4b9641a92ad15017cc4/drf_spectacular_jsonapi/schemas/plumbing.py#L85)

I need to lookup the schema for the primary key. But how can i get the relevant primary key attribute name from the serializer object? In case of simple `Serializer` instances, is there any pk (json:api id)?

**Comment by sliverc** [comment]
DJA currently does not support serializing of instances without an `pk` attribute on the instance. There is an issue at https://github.com/django-json-api/django-rest-framework-json-api/issues/1126 and a working in progress PR https://github.com/django-json-api/django-rest-framework-json-api/pull/1127 to add such support.
