### ISSUE TITLE
Translations of title and descriptions shall be part of the schema

### ISSUE THREAD

**Issue by jokiefer** [jokiefer/drf-spectecular-json-api#8]
### Raised initially as discussion

- [X] Discussion was held

### Proposed functionality

The schema shall contains the metadata for properties, such as title and description

**Comment by jokiefer** [comment]
@tfranzel
I stumbled over the [is_trivial_string_variation](https://github.com/tfranzel/drf-spectacular/blob/a60b8c4ab5871b023dec20073797b9ef631f16d6/drf_spectacular/openapi.py#L983) check, which is used to ignore "duplicate" titles. 
So if the serializer field for example is named `genre` and the `verbose_name` were set to a translatable string such as `_("Genre")`, your code wont attach the title.

In my POV, if the user explicitly set the `verbose_name` the string shall be taken as it is. Only if it is exactly the same it would be redundant. 

What do you think?

**Comment by tfranzel** [comment]
> In my POV, if the user explicitly set the verbose_name the string shall be taken as it is. Only if it is exactly the same it would be redundant.

I agree in theory, but we are sometimes unable to distinguish user-provided values from DRF's auto-generated values. This function accounts for the small difference DRF introduces between the actual name and the auto-generated `field_name`/`label`. 

We simply assume that if the `verbose_name`(?) is identical to the name, DRF was fumbling with it. I think if that function returns `true`, there would be basically zero additional information so we discard it.

Translations -- if substantially different (e.g. `"Génrë" != "genre"`) --  should be included though. That should be already the case I believe. Does that make sense? Do you still see a todo here?

**Comment by jokiefer** [comment]
I fully agree with you. But let me explain my vision of using the openapi schema in a frontend.

There are many ways to build frontends for restfull api's. But the special thing i saw in the combination of using json:api and a fully serving openapi schema is, that i can implement a single json:api client which can initialize fully from the schema. Cause the json:api data framework is stable and only the resources/django-models are floating. For simple crud applications, there is no need of implementing pojos or any `copy pasted` model definition in the backend and frontend. So the frontend can fully initialize all there components from the schema. Forms, tables, autocomplete fields and so on can be initialized by the meta information from the schema.

So if the user wan'ts upper case titles for fields or models, the user won't get them served by the schema for now. Cause the `is_trivial_string_variation()` will filter them out.The user needs to `fumbling` the `verbose_name` inside the frontend. But in my POV this is the keefeature of a fully serving openapi schemas. Maybe there are redundant information, but there is a single place of truth for metainformation. 

So if you don't wont to drop the uppercase condition, what if we could implement a setting to let the user decide what he wants to get?

**Comment by tfranzel** [comment]
Imho, dropping that condition will lead to noisy schema with basically zero added information. This was very carefully crafted. Adding a feature for this seems rather useless for spectacular itself. I don't see a good argument from a plain OpenAPI perspective, not to discount your use-case though.

However, since you subclass `AutoSchema` anyway, why not do this?

```python
class JsonApiAutoSchema(AutoSchema):
    def _get_serializer_field_meta(self, field, direction):
        meta = super()._get_serializer_field_meta(field, direction)
        if field.label:
            meta['title'] = str(field.label)
        return meta

    ...
```

This does not reinvent the wheel, is very compact and minimally invasive.
